### ISSUE TITLE
[HELP] - Terminal session does not start

### ISSUE THREAD

**Issue by antton** [play-with-go/play-with-go#392]
**Describe the bug**
When I try to launch any guide on local, the terminal does not initialize, and I get the following error message on docker logs.

controller_1  | failed to execute all presteps: failed to create prestep request for {http   cmd_gitea:8080 /newuser  false false   }: Post "http://cmd_gitea:8080/newuser": EOF
cmd_gitea_1   | server.go:3230: http: panic serving 172.18.0.5:44722: failed to create user: token is required
cmd_gitea_1   | goroutine 27 [running]:
cmd_gitea_1   | net/http.(*conn).serve.func1()
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:1850 +0xbf
cmd_gitea_1   | panic({0x9f64a0, 0xc00046a3d0})
cmd_gitea_1   | 	/usr/local/go/src/runtime/panic.go:890 +0x262
cmd_gitea_1   | main.raise(...)
cmd_gitea_1   | 	/root/.cache/go/gomodcache/github.com/play-with-go/gitea@v0.0.0-20221003164140-c14d636df530/cmd/gitea/flag.go:223
cmd_gitea_1   | main.(*serveCmd).createUser(0xc00029cd00)
cmd_gitea_1   | 	/root/.cache/go/gomodcache/github.com/play-with-go/gitea@v0.0.0-20221003164140-c14d636df530/cmd/gitea/serve.go:228 +0x4db
cmd_gitea_1   | main.(*serveCmd).newUser(0xc00029cd00, 0xc0003f0018)
cmd_gitea_1   | 	/root/.cache/go/gomodcache/github.com/play-with-go/gitea@v0.0.0-20221003164140-c14d636df530/cmd/gitea/serve.go:146 +0x3e
cmd_gitea_1   | main.(*serveCmd).run.func4({0xb585b0, 0xc000362000}, 0xc00006e700)
cmd_gitea_1   | 	/root/.cache/go/gomodcache/github.com/play-with-go/gitea@v0.0.0-20221003164140-c14d636df530/cmd/gitea/serve.go:103 +0x236
cmd_gitea_1   | net/http.HandlerFunc.ServeHTTP(0xc000362000?, {0xb585b0?, 0xc000362000?}, 0xa6cc4e?)
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:2109 +0x2f
cmd_gitea_1   | net/http.(*ServeMux).ServeHTTP(0x0?, {0xb585b0, 0xc000362000}, 0xc00006e700)
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:2487 +0x149
cmd_gitea_1   | net/http.serverHandler.ServeHTTP({0xb572c8?}, {0xb585b0, 0xc000362000}, 0xc00006e700)
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:2947 +0x30c
cmd_gitea_1   | net/http.(*conn).serve(0xc0003be000, {0xb58b00, 0xc0002d4c90})
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:1991 +0x607
cmd_gitea_1   | created by net/http.(*Server).Serve
cmd_gitea_1   | 	/usr/local/go/src/net/http/server.go:3102 +0x4db

**To Reproduce**
1. Download this repository.
2. Launch _docker-compose up_
3. Try to get inside any guide on localhost:4000 (via web browser)
4. Check the docker-compose logs output

**Comment by myitcv** [comment]
It does appear to be a bug that PWG currently requires a token to connected to gopher.live.

Per the [contribution guidelines](https://github.com/play-with-go/play-with-go/blob/main/CONTRIBUTING.md#prerequisite-1---gopherlive-contributor-account), this should only be a requirement for a guide that requires the `gitea` prestep.
